import type {
  Database as GeneratedDatabase,
  Json as GeneratedJson,
} from '@/app/types/database.generated';

/**
 * App-facing aliases for the schema generated by `npm run db:types`.
 * Regenerate `database.generated.ts` after every migration change.
 */
export type Database = GeneratedDatabase;
export type Json = GeneratedJson;

export type ScholarRow = Database['public']['Tables']['scholars']['Row'];
export type PublicScholarRow = Database['public']['Views']['public_scholars']['Row'];
export type PrivateScholarRow = Pick<
  ScholarRow,
  | 'id'
  | 'status'
  | 'year'
  | 'first'
  | 'middle'
  | 'last'
  | 'school'
  | 'major'
  | 'currentCity'
  | 'currentState'
  | 'description'
  | 'company'
  | 'imageUrl'
  | 'bio'
  | 'email'
  | 'cellPhone'
>;
export type EventRow = Database['public']['Tables']['events']['Row'];
export type NewsRow = Database['public']['Tables']['news']['Row'];
export type JobPostingRow = Database['public']['Tables']['job_postings']['Row'];
export type MentorshipSignupRow = Database['public']['Tables']['mentorship_signups']['Row'];
export type GalleryAlbumRow = Database['public']['Tables']['gallery_albums']['Row'];
